### ISSUE TITLE
Memory allocation problems, 32 bits or 64 bits matter?

### ISSUE THREAD

**Issue by Pedrodpj92** [topepo/C5.0#15]
Hello!

I am trying to train a model with a dataset around 2 million rows and 600 columns. I got the following error:

Error in paste(apply(x, 1, paste, collapse = ","), collapse = "\n") : result would exceed 2^31-1 bytes

Based on this issue ( https://github.com/topepo/C5.0/issues/4 ) I guess that there is a problem related to the maximum allocation length, but I am not sure. Is this error only caused in 32 bits machine? Would it run properly in a 64 bits machine with enough RAM?

**Comment by topepo** [comment]
It's a weird R limitation. I did find a [potential solution](https://github.com/joey711/phyloseq/pull/328/commits/0508ae73d2a37ad91dc59d211b20807519b7dae0) but it might take some time to implement.

**Comment by shouldsee** [comment]
Is there any existing solution for this yet?

**Comment by topepo** [comment]
No not yet. I'm hoping to get to it in a month or so.

**Comment by shouldsee** [comment]
> It's a weird R limitation. I did find a [potential solution](https://github.com/joey711/phyloseq/pull/328/commits/0508ae73d2a37ad91dc59d211b20807519b7dae0) but it might take some time to implement.

Seems they circumvent the allocation problem rather than "solve" it.

**Comment by topepo** [comment]
Agreed. I don't have time to work on this. If someone would like to make a PR, that would be great.

**Comment by sarasanzlucio** [comment]
Hey,
I found a solution to this problem and posted it in [stackoverflow](https://stackoverflow.com/questions/68123447/c5-0-package-error-in-pasteapplyx-1-paste-collapse-collapse-n). Basically, as the limitation of the size of the string is an R matter, I create a character vector instead (containing the string sliced) in order to pass it to the C code so that there it can be concatenated and the algorithm can continue as is.
